### PR TITLE
Add plot_weights_hook with an example to plot weights during training

### PR DESCRIPTION
**Pull request by EmbraceLife**
the details of how to use them can be found in the commits description below.

### CODE REVIEW

**Comment by ajsyp** [comment]
Anything wrong / do you not want this to be merged?

**Comment by EmbraceLife** [comment]
Thanks Adam, if you think this feature is good to have in kur, I would like it to be merged. However, I have changed it a little bit. I can update this and PR again, if having this feature does not hurt kur.

**Comment by ajsyp** [comment]
Just feel free to make/push any updates to your PR, and comment on it here. That way, I can track its development/evolution a little better. Don't worry about closing/re-opening it every time you want to make some changes.

**Comment by EmbraceLife** [comment]
What is the easy way to sync my kur fork with deepgram/kur?

I have been avoiding this for a while, but it becomes time consuming now.

**Comment by ajsyp** [comment]
There are lots of techniques and schools of thought about keeping `git` up-to-date with a remote (e.g., merging, rebasing, branches, etc.). I'd suggest you read up on them and decide for yourself. But if you want to play around with a quick-and-dirty method, try duplicating (or tagging, if you're comfortable using tags in git) your repository locally, adding the original (non-forked) Kur as a remote (`git remote add upstream https://github.com/deepgram/kur.git`), and then merging it in (`git pull upstream master`, `git merge upstream/master`) and see if you're happy with the results. But all of this requires some knowledge of how git works, so you should read up on it first.

**Comment by EmbraceLife** [comment]
The `cifar.yml` and `mnist.yml` work without error. I have no idea why the Travis CI above marks them with error. 
What should I do about them?

**Comment by EmbraceLife** [comment]
I have added `mode=None` to all Traininghooks as well in the latest commit.

**Comment by EmbraceLife** [comment]
Could you give me some guidance or suggestions on how to improve on the PR codes, if they are not ready to be pulled?  Thanks

**Comment by EmbraceLife** [comment]
my previous commit (which reported as "All checks have failed") is to set all examples back to the original examples in kur official repo. 
Why "All checks have failed"? What should I do about it? Thanks

**Comment by ajsyp** [comment]
On my screen, right under "All checks have failed" is a line that says: "continuous-integration/travis-ci/pr -- The Travis CI build failed    Details". If you have the "Details" button, it should show you what happened.

In this case, it looks like `pip` simply timed out trying to install dependencies on the CI server. So don't worry about it.

**Comment by EmbraceLife** [comment]
In the latest commit, I have done the following: 
1. remove unnecessary comments; 
2. create an error message to tell use how plot_weights function behave; 
3. whether plot_conv_weights function can plot RNN weights or not, I will try it tomorrow; 
4. leave other hooks unchanged, such as kurhub_hook.py, slack_hook; 
5. I have no experience in writing copyright notice, could you offer an example of "a better copyright notice"?
Thanks!

**Comment by EmbraceLife** [comment]
> Plotting every n epochs. If n=2, you currently plot after epochs 1, 2, 4, 6, ... Seems like it should be after epochs 2, 4, 6, ... or 1, 3, 5, ....
(I am not sure about what exactly this suggestion wants me to change)

My intention is, when plot_weights is required, users can decide when to plot weights again, but weights on epoch 1 will automatically plotted (for comparison). If set n=100, beside weight plotting on epoch 1, kur will plot weights when it comes to epoch 100, 200, 300...

Is it ok? or do I have to change it somehow?

**Comment by EmbraceLife** [comment]
I have managed to make `plot_conv_layers` work. But I should not commit this before this current PR get accepted, right?

**Comment by EmbraceLife** [comment]
in the last 3 commit, the first two are docs for plot_weights feature. The last commit is to enable plot for RNN weights. So by now, `plot_weights_hook.py` handles 3 types of weights for plotting (see figure from the link below)
[plot 3 types of weights with 3 functions](https://lh3.googleusercontent.com/kcPM4sV4kImYzpvZDEpj6FFfxJgOAS-7DxS71KJ2RryBdhGMbMlkES-rhRFnMOvTEt2UgKb8esHEexOo2s_RdnZwmXXfW-0Zz6EYufLGiXFvZOOHhtafxK3AFropkI3Efqg7TpWwurrpcAW_NH0gfdNIlFKSaU06E5DmM2aVi_t284BEXAvYx1m0tTRHsG9ptijeRAFeIgaWDxiS-aiuQ3CexSgP99_6J9NodWZEU_LrJgo_3v0cNmoZKK4Y2LkKZMjajD9lqCVRRAmREd6Mz9_6BdcwX_lrIB4DNyqQWa5lVhjb5qDJZQ00YvovbJmGb1cYfX6R-cE3-qqQYtltrzSGunyFRfbCLYwDyxdStbj3I8uZpf5UM50K7XKR1NwNme6pRITJE1Iyv3O8uPLrgVG3rV0jt_sJPFUlLQbJLd73vJI5K1ShGf_97QDwnBTl1NBe4mmHFASyGGeT_rmid2XzXa8L1ZmL-mSfE6m6tBhC6uO1Qc_o6a689iIvURcR3CgLZskXpxjYB_k3sTWrgUnB5zdk9G_fMylWlwpXS_KJYW7aeFEtpj3nuwJ378XnmdM0x3y6jSaGaUOrTqgnBAc2k3az70aXiFVsqVFH5SqOeqnbr3Ch=w1282-h1136-no)

I used `kur/examples/language_model` example to experiment on `plot_rnn_weights`. It can plot, but `plot_rnn_weights` keep plotting 36 grids which I have no idea why. Could you have me have a look? Thanks 

so far, I have dealt with all suggestions you made above. Meanwhile I have managed to get `leakyReLU` activation work and `plot_conv_layers` work. When could I make a PR for them?

**Comment by EmbraceLife** [comment]
sorry, I was not intended to commit the leakyReLU before the current PR is accepted.

**Comment by ajsyp** [comment]
This is looking pretty good. Can we remove the leaky ReLU code from this PR, restrict changes in documentation strictly to new documentation pertaining to using the PR, and eliminate any changes to the stock example Kurfiles? I think we'll be in a good position to merge at that point.

FYI, I think you _should_ be able to create multiple PRs by simply maintaining multiple branches on your Kur fork, and submitting a PR for each fork. That way, you can continue work on the leaky ReLU in parallel to the plot_weights stuff.

And sorry for the delay: I've been heads-down in some high-priority Deepgram stuff. All good stuff :)

**Comment by EmbraceLife** [comment]
Thanks for your replies. I discovered much better ways of doing visualizations, so I will try to implement those later. This PR can be dropped.

**Comment by ajsyp** [comment]
Closing for now, until the PR can be cleaned up.

**Pull request closed without merging**
