### PR TITLE
Add min_duration option to speechrec supplier.

### PR DESCRIPTION
**Pull request by antho-rousseau**
Added an option to provide a minimum duration for speech examples, just like the maximum duration one.

### CODE REVIEW

**Comment by ajsyp** [comment]
This looks great @antho-rousseau! One request before we merge it in: a couple of your edited lines are indented with spaces; we use tabs in Kur, so do you mind replace "4 spaces" with "1 tab", and then we'll pull it in?

**Comment by antho-rousseau** [comment]
@ajsyp no problem, should be good to go now!

**Comment by ajsyp** [comment]
It looks like line 429, part of the `SpeechRecognitionSupplier.__init__` signature still has spaces preceding it:

```
                max_frequency=None, vocab=None, samples=None, *args, **kwargs):
```

**Comment by antho-rousseau** [comment]
Oh yes, right, didn't saw this one! Thanks, should be good this time!

**Comment by ajsyp** [comment]
Awesome, looks great, thanks!

**Pull request merged**
